"""Built-in provider configurations.

Single source of truth for all provider URLs, models, and capabilities.
Every surface in the platform imports from here — no more hardcoded constants.
"""

from .models import ProviderConfig, ProviderType

BUILTIN_PROVIDERS: dict[str, ProviderConfig] = {
    # ── Tier 1: Primary providers ──
    "openai": ProviderConfig(
        id="openai",
        name="OpenAI",
        api_type=ProviderType.OPENAI_COMPATIBLE,
        base_url="https://api.openai.com/v1",
        default_model="gpt-4o",
        models=["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-3.5-turbo", "o1", "o1-mini"],
        env_key_name="OPENAI_API_KEY",
        supports_vision=True,
        supports_tools=True,
        supports_json_mode=True,
    ),
    "anthropic": ProviderConfig(
        id="anthropic",
        name="Anthropic",
        api_type=ProviderType.ANTHROPIC,
        base_url="https://api.anthropic.com/v1",
        default_model="claude-sonnet-4-20250514",
        models=["claude-sonnet-4-20250514", "claude-3-5-sonnet-20241022", "claude-3-haiku-20240307"],
        env_key_name="ANTHROPIC_API_KEY",
        supports_vision=True,
        supports_tools=True,
        supports_json_mode=False,  # Anthropic uses prefill, not response_format
    ),
    "groq": ProviderConfig(
        id="groq",
        name="Groq",
        api_type=ProviderType.OPENAI_COMPATIBLE,
        base_url="https://api.groq.com/openai/v1",
        default_model="llama-3.3-70b-versatile",
        models=["llama-3.3-70b-versatile", "llama-3.1-70b-versatile", "mixtral-8x7b-32768"],
        env_key_name="GROQ_API_KEY",
        supports_vision=False,
        supports_tools=True,
        supports_json_mode=True,
    ),
    "google": ProviderConfig(
        id="google",
        name="Google Gemini",
        api_type=ProviderType.GOOGLE,
        base_url="https://generativelanguage.googleapis.com/v1beta",
        default_model="gemini-2.0-flash",
        models=["gemini-2.0-flash", "gemini-1.5-pro", "gemini-1.5-flash"],
        env_key_name="GEMINI_API_KEY",
        env_key_aliases=["GOOGLE_API_KEY", "GEMINI_API_KEY_2"],
        supports_vision=True,
        supports_tools=True,
        supports_json_mode=True,
    ),
    # ── Tier 2: Additional providers ──
    "deepseek": ProviderConfig(
        id="deepseek",
        name="DeepSeek",
        api_type=ProviderType.OPENAI_COMPATIBLE,
        base_url="https://api.deepseek.com/v1",
        default_model="deepseek-chat",
        models=["deepseek-chat", "deepseek-coder"],
        env_key_name="DEEPSEEK_API_KEY",
        supports_vision=False,
        supports_tools=True,
        supports_json_mode=True,
    ),
    "mistral": ProviderConfig(
        id="mistral",
        name="Mistral AI",
        api_type=ProviderType.OPENAI_COMPATIBLE,
        base_url="https://api.mistral.ai/v1",
        default_model="mistral-large-latest",
        models=["mistral-large-latest", "mistral-medium-latest", "mistral-small-latest"],
        env_key_name="MISTRAL_API_KEY",
        supports_vision=False,
        supports_tools=True,
        supports_json_mode=True,
    ),
    "together": ProviderConfig(
        id="together",
        name="Together AI",
        api_type=ProviderType.OPENAI_COMPATIBLE,
        base_url="https://api.together.xyz/v1",
        default_model="meta-llama/Llama-3-70b-chat-hf",
        models=["meta-llama/Llama-3-70b-chat-hf", "mistralai/Mixtral-8x7B-Instruct-v0.1"],
        env_key_name="TOGETHER_API_KEY",
        supports_vision=False,
        supports_tools=False,
        supports_json_mode=True,
    ),
    "perplexity": ProviderConfig(
        id="perplexity",
        name="Perplexity",
        api_type=ProviderType.OPENAI_COMPATIBLE,
        base_url="https://api.perplexity.ai",
        default_model="llama-3.1-sonar-large-128k-online",
        models=["llama-3.1-sonar-large-128k-online", "llama-3.1-sonar-small-128k-online"],
        env_key_name="PERPLEXITY_API_KEY",
        supports_vision=False,
        supports_tools=False,
        supports_json_mode=False,
    ),
    "fireworks": ProviderConfig(
        id="fireworks",
        name="Fireworks AI",
        api_type=ProviderType.OPENAI_COMPATIBLE,
        base_url="https://api.fireworks.ai/inference/v1",
        default_model="accounts/fireworks/models/llama-v3p1-70b-instruct",
        models=["accounts/fireworks/models/llama-v3p1-70b-instruct"],
        env_key_name="FIREWORKS_API_KEY",
        supports_vision=False,
        supports_tools=True,
        supports_json_mode=True,
    ),
    "openrouter": ProviderConfig(
        id="openrouter",
        name="OpenRouter",
        api_type=ProviderType.OPENAI_COMPATIBLE,
        base_url="https://openrouter.ai/api/v1",
        default_model="openai/gpt-4o",
        models=["openai/gpt-4o", "anthropic/claude-3-opus", "google/gemini-pro"],
        env_key_name="OPENROUTER_API_KEY",
        headers={"HTTP-Referer": "https://resonantgenesis.com"},
        supports_vision=True,
        supports_tools=True,
        supports_json_mode=True,
    ),
    "cohere": ProviderConfig(
        id="cohere",
        name="Cohere",
        api_type=ProviderType.OPENAI_COMPATIBLE,
        base_url="https://api.cohere.ai/v1",
        default_model="command-r-plus",
        models=["command-r-plus", "command-r"],
        env_key_name="COHERE_API_KEY",
        supports_vision=False,
        supports_tools=True,
        supports_json_mode=True,
    ),
    "bedrock": ProviderConfig(
        id="bedrock",
        name="AWS Bedrock",
        api_type=ProviderType.OPENAI_COMPATIBLE,
        base_url="https://bedrock-runtime.us-east-2.amazonaws.com/v1",
        default_model="anthropic.claude-3-5-sonnet-20241022-v2:0",
        models=[
            "anthropic.claude-3-5-sonnet-20241022-v2:0",
            "anthropic.claude-3-haiku-20240307-v1:0",
            "meta.llama3-1-70b-instruct-v1:0",
            "amazon.nova-pro-v1:0",
            "amazon.nova-lite-v1:0",
        ],
        env_key_name="AWS_BEDROCK_API_KEY",
        supports_vision=True,
        supports_tools=True,
        supports_json_mode=True,
    ),
}

# Provider alias map — normalize user input to canonical provider IDs
PROVIDER_ALIASES: dict[str, str] = {
    "chatgpt": "openai",
    "gpt": "openai",
    "claude": "anthropic",
    "gemini": "google",
    "llama": "groq",
    "aws": "bedrock",
    "amazon": "bedrock",
}

# Default fallback order when no provider is specified
DEFAULT_FALLBACK_ORDER: list[str] = [
    "openai",
    "anthropic",
    "groq",
    "google",
    "deepseek",
    "mistral",
]
